apiVersion: v1
kind: Route
metadata:
  annotations:
    nginx.router.openshift.io/balance: least_conn
    nginx.router.openshift.io/port: "31001"
    nginx.router.openshift.io/protocol: tcp
  labels:
    app: kafka-infra
  name: kafka-broker1.INTERNAL_DNS
spec:
  host: kafka-broker1.INTERNAL_DNS
  port:
    targetPort: external
  to:
    kind: Service
    name: kafka-infra-1
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
    host: kafka-broker1.INTERNAL_DNS
    routerName: nginx.router.tcp.udp
    wildcardPolicy: None
