apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-infra
  name: kafka-infra-2
spec:
  ports:
  - name: external
    port: 31002
    protocol: TCP
    targetPort: 31002
  selector:
    app: kafka-infra
    statefulset.kubernetes.io/pod-name: kafka-infra-2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
