apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka-infra
  name: kafka-infra-1
spec:
  ports:
  - name: external
    port: 31001
    protocol: TCP
    targetPort: 31001
  selector:
    app: kafka-infra
    statefulset.kubernetes.io/pod-name: kafka-infra-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
