apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-infra
  name: kafka-infra
spec:
  clusterIP: None
  ports:
  - name: jmx
    port: 8999
    protocol: TCP
    targetPort: 8999
  - name: internal
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: external
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka-infra
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
